// <auto-generated />
using System;
using Database.AppDbContextModels;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Database.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20261002070958_RestrictAdminUsernames")]
    partial class RestrictAdminUsernames
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("Database.AppDbContextModels.AdminUser", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint")
                        .HasColumnName("id");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("created_at");

                    b.Property<long?>("CreatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("created_by");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("email");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_active");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)")
                        .HasColumnName("is_deleted");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("varchar(255)")
                        .HasColumnName("password_hash");

                    b.Property<Guid>("PublicId")
                        .HasColumnType("char(36)")
                        .HasColumnName("public_id");

                    b.Property<string>("UniqueEmail")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(254)
                        .HasColumnType("varchar(254)")
                        .HasColumnName("unique_email")
                        .HasComputedColumnSql("CASE WHEN is_deleted = 1 AND is_active = 0 THEN NULL ELSE email END", true);

                    b.Property<string>("UniqueUserName")
                        .ValueGeneratedOnAddOrUpdate()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("unique_user_name")
                        .HasComputedColumnSql("CASE WHEN is_deleted = 1 AND is_active = 0 THEN NULL ELSE user_name END", true);

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)")
                        .HasColumnName("updated_at");

                    b.Property<long?>("UpdatedBy")
                        .HasColumnType("bigint")
                        .HasColumnName("updated_by");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("varchar(20)")
                        .HasColumnName("user_name");

                    b.HasKey("Id")
                        .HasName("pk_admin_users");

                    b.HasIndex("CreatedBy")
                        .HasDatabaseName("ix_admin_users_created_by");

                    b.HasIndex("PublicId")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_public_id");

                    b.HasIndex("UniqueEmail")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_unique_email");

                    b.HasIndex("UniqueUserName")
                        .IsUnique()
                        .HasDatabaseName("ix_admin_users_unique_user_name");

                    b.HasIndex("UpdatedBy")
                        .HasDatabaseName("ix_admin_users_updated_by");

                    b.ToTable("admin_users", (string)null);
                });

            modelBuilder.Entity("Database.AppDbContextModels.AdminUser", b =>
                {
                    b.HasOne("Database.AppDbContextModels.AdminUser", "CreatedByUser")
                        .WithMany("CreatedUsers")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_admin_users_admin_users_created_by");

                    b.HasOne("Database.AppDbContextModels.AdminUser", "UpdatedByUser")
                        .WithMany("UpdatedUsers")
                        .HasForeignKey("UpdatedBy")
                        .OnDelete(DeleteBehavior.Restrict)
                        .HasConstraintName("fk_admin_users_admin_users_updated_by");

                    b.Navigation("CreatedByUser");

                    b.Navigation("UpdatedByUser");
                });

            modelBuilder.Entity("Database.AppDbContextModels.AdminUser", b =>
                {
                    b.Navigation("CreatedUsers");

                    b.Navigation("UpdatedUsers");
                });
#pragma warning restore 612, 618
        }
    }
}
