@baseUrl = http://localhost:5131
@publicId = 315f4599-1404-4f42-890c-c96b7cebde16

### List administrative users
GET {{baseUrl}}/api/admin_user
Accept: application/json

### Get an administrative user by public ID
# Set @publicId to the "data" value returned by the create request.
GET {{baseUrl}}/api/admin_user/{{publicId}}
Accept: application/json

### Create an administrative user
POST {{baseUrl}}/api/admin_user
Content-Type: application/json

{
  "userName": "htooo",
  "email": "htoo2@gmail.com",
  "password": "Htoo",
  "isActive": true
}

### Update an administrative user
PUT {{baseUrl}}/api/admin_user/{{publicId}}
Content-Type: application/json

{
  "userName": "httooo",
  "email": "htoo@gmail",
  "isActive": true
}

### Soft-delete an administrative user
DELETE {{baseUrl}}/api/admin_user/{{publicId}}
Accept: application/json
