@baseUrl = http://localhost:5131
@publicId = c3908ba6-c6d2-454f-9646-25c3bdaae699

### List administrative users
GET {{baseUrl}}/api/admin_user
Accept: application/json

### Get an administrative user by public ID
# Set @publicId to the "data" value returned by the create request.
GET {{baseUrl}}/api/admin_user/{{publicId}}
Accept: application/json

### Create an administrative user
POST {{baseUrl}}/api/admin_user
Content-Type: application/json

{
  "userName": "htoo",
  "email": "htoo@gmail.com",
  "password": "Htoo@123",
  "isActive": true
}

### Update an administrative user
PUT {{baseUrl}}/api/admin_user/{{publicId}}
Content-Type: application/json

{
  "userName": "httooo",
  "email": "htoo3@gmail.com",
  "isActive": true
}

### Change an administrative user's password
PUT {{baseUrl}}/api/admin_user/{{publicId}}/password
Content-Type: application/json

{
  "newPassword": "NewHtoo@456"
}

### Partially update an administrative user
PATCH {{baseUrl}}/api/admin_user/{{publicId}}
Content-Type: application/json

{
  "userName": null,
  "email": "htoo1@gmail",
  "isActive": null
}

### Soft-delete an administrative user
DELETE {{baseUrl}}/api/admin_user/{{publicId}}
Accept: application/json
